# Generated by Django 4.1.6 on 2023-04-11 20:14

import StudentUnion.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DueReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('file_name', models.ImageField(null=True, upload_to=StudentUnion.models.receipt_directory_path)),
                ('account_name', models.CharField(max_length=255, null=True)),
                ('account_address', models.CharField(max_length=500, null=True)),
                ('our_reference', models.CharField(max_length=16, null=True)),
                ('transaction_amount', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(3000), django.core.validators.MaxValueValidator(3000)])),
                ('transaction_account', models.BigIntegerField(null=True)),
                ('is_validated', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Due Receipts',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_name', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SessionYearModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_start_year', models.IntegerField(choices=[(2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=StudentUnion.models.current_year, null=True)),
                ('session_end_year', models.IntegerField(choices=[(2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=StudentUnion.models.current_year, null=True)),
            ],
            options={
                'verbose_name_plural': 'Academic Year',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default=('female', 'Female'), max_length=30)),
                ('address', models.TextField(null=True)),
                ('matricule_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=StudentUnion.models.user_directory_path)),
                ('my_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentUnion.department')),
                ('my_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentUnion.level')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
