# Generated by Django 4.1.6 on 2023-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentUnion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_validated_committee_member',
        ),
    ]
