# Generated by Django 4.1.6 on 2023-04-11 21:39

import StudentUnion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentUnion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duereceipt',
            name='department',
            field=models.CharField(choices=[('FET', 'FET'), ('COT', 'COT'), ('ASTI', 'ASTI'), ('ENSET', 'ENSET')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='duereceipt',
            name='level',
            field=models.IntegerField(choices=[(200, 200), (300, 300), (400, 400), (450, 450)], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=StudentUnion.models.user_directory_path),
        ),
    ]
