# Generated by Django 4.1.6 on 2023-03-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentUnion', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='duereceipt',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_level', to='StudentUnion.level'),
        ),
        migrations.AlterField(
            model_name='duereceipt',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts_department', to='StudentUnion.department'),
        ),
    ]
