# Generated by Django 4.1.6 on 2023-03-31 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentUnion', '0006_alter_duereceipt_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duereceipt',
            name='department',
            field=models.ForeignKey(choices=[('College of Technology', 'College of Technology'), ('FET', 'FET'), ('ASTI', 'ASTI')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts_department', to='StudentUnion.department'),
        ),
        migrations.AlterField(
            model_name='duereceipt',
            name='level',
            field=models.ForeignKey(choices=[(200, 200), (300, 300), (400, 400)], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_level', to='StudentUnion.level'),
        ),
    ]
