# Generated by Django 4.1.6 on 2023-04-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentUnion', '0008_student_my_department_student_my_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='my_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentUnion.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='my_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentUnion.level'),
        ),
    ]
