# Generated by Django 4.1.6 on 2023-04-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentUnion', '0009_alter_student_my_department_alter_student_my_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duereceipt',
            name='receipt_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_receipts', to='StudentUnion.student'),
        ),
    ]
